"""add module_generation_rework schema foundation

Revision ID: 08d567a6683f
Revises: 0fe7e24824fa
Create Date: 2026-08-02 20:28:28.135701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08d567a6683f'
down_revision = '0fe7e24824fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('module_id', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_conversation_messages_module_id', 'modules', ['module_id'], ['id'])

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('context_summary', sa.JSON(), nullable=True))

    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_plan', sa.JSON(), nullable=False, server_default='[]'))

    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deep_search_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_column('deep_search_enabled')

    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.drop_column('activity_plan')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('context_summary')

    with op.batch_alter_table('conversation_messages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_conversation_messages_module_id', type_='foreignkey')
        batch_op.drop_column('module_id')

    # ### end Alembic commands ###
