"""Add tavily_api_key to user_settings

Revision ID: 0fe7e24824fa
Revises: 281a13021e44
Create Date: 2026-07-31 08:48:34.002013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fe7e24824fa'
down_revision = '281a13021e44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tavily_api_key', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_column('tavily_api_key')

    # ### end Alembic commands ###
