"""add video embedding setting

Revision ID: 3233479dcbab
Revises: e9111238569b
Create Date: 2026-08-05 15:48:44.841001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3233479dcbab'
down_revision = 'e9111238569b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('video_embedding_enabled', sa.Boolean(), nullable=False, server_default=sa.false())
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_column('video_embedding_enabled')

    # ### end Alembic commands ###
