"""add interview_topics_covered and direction_change_understanding

Revision ID: 3afdd7e98e6b
Revises: cf828066c025
Create Date: 2026-08-07 18:59:53.064567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3afdd7e98e6b'
down_revision = 'cf828066c025'
branch_labels = None
depends_on = None


def upgrade():
    # interview_topics_covered is NOT NULL with no application-level
    # default that reaches existing rows - server_default backfills
    # existing courses to an empty list, matching the model's own
    # default=list (same pattern as web_search_supplement_enabled/
    # context_summary's earlier migrations).
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interview_topics_covered', sa.JSON(), nullable=False, server_default='[]'))

    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direction_change_understanding', sa.Text(), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.drop_column('direction_change_understanding')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('interview_topics_covered')

    # ### end Alembic commands ###
