"""Add byom_model to user_settings

Revision ID: 6624a6f26be3
Revises: ff940063365a
Create Date: 2026-07-31 07:56:31.223376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6624a6f26be3'
down_revision = 'ff940063365a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_provider_byom_model', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_column('model_provider_byom_model')

    # ### end Alembic commands ###
