"""Add source_materials and user_settings tables

Revision ID: 9a396a383314
Revises: 203b1047d3ec
Create Date: 2026-07-30 21:11:59.366074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a396a383314'
down_revision = '203b1047d3ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('feedback_tone', sa.String(), nullable=False),
    sa.Column('thumbnail_generation_enabled', sa.Boolean(), nullable=False),
    sa.Column('model_provider_tier', sa.String(), nullable=False),
    sa.Column('model_provider_hosted_provider', sa.String(), nullable=True),
    sa.Column('model_provider_api_key', sa.String(), nullable=True),
    sa.Column('model_provider_byom_endpoint', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_materials',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('course_id', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source_materials')
    op.drop_table('user_settings')
    # ### end Alembic commands ###
