"""add web search supplement and visual aids opt-ins

Revision ID: accd429f6508
Revises: f8628ffc61a8
Create Date: 2026-08-04 20:20:27.457995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'accd429f6508'
down_revision = 'f8628ffc61a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('web_search_supplement_enabled', sa.Boolean(), nullable=False, server_default=sa.false())
        )

    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('visual_aids_enabled', sa.Boolean(), nullable=False, server_default=sa.false())
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_column('visual_aids_enabled')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('web_search_supplement_enabled')

    # ### end Alembic commands ###
