"""add activity completed_at and weekly goal

Revision ID: cf664e6a7644
Revises: accd429f6508
Create Date: 2026-08-04 21:18:45.549532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf664e6a7644'
down_revision = 'accd429f6508'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weekly_goal_activities', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_column('weekly_goal_activities')

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_column('completed_at')

    # ### end Alembic commands ###
