"""add onboarding completed flag

Revision ID: e11e38bcd24e
Revises: f0e05984ccb5
Create Date: 2026-08-06 21:10:43.304301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e11e38bcd24e'
down_revision = 'f0e05984ccb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default=true (not the model's own default=False) is deliberate:
    # this backfills *existing* rows as already onboarded, so upgrading
    # doesn't make an existing install suddenly see the first-time modal.
    # Only a genuinely new row (created after this migration) gets False,
    # via the model's own column default.
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('onboarding_completed', sa.Boolean(), nullable=False, server_default=sa.true())
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_column('onboarding_completed')

    # ### end Alembic commands ###
