"""add course thumbnail image and image generation settings

Revision ID: e9111238569b
Revises: cf664e6a7644
Create Date: 2026-08-04 21:35:04.278595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9111238569b'
down_revision = 'cf664e6a7644'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_image_path', sa.String(), nullable=True))

    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_generation_model', sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column(
                'image_generation_use_completion_credentials',
                sa.Boolean(),
                nullable=False,
                server_default=sa.true(),
            )
        )
        batch_op.add_column(sa.Column('image_generation_api_key', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_column('image_generation_api_key')
        batch_op.drop_column('image_generation_use_completion_credentials')
        batch_op.drop_column('image_generation_model')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('thumbnail_image_path')

    # ### end Alembic commands ###
