"""add activity_id to conversation messages

Revision ID: f0e05984ccb5
Revises: f446ffbc5572
Create Date: 2026-08-06 17:30:09.171168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0e05984ccb5'
down_revision = 'f446ffbc5572'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_id', sa.String(), nullable=True))
        batch_op.create_foreign_key(
            'fk_conversation_messages_activity_id', 'activities', ['activity_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_messages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_conversation_messages_activity_id', type_='foreignkey')
        batch_op.drop_column('activity_id')

    # ### end Alembic commands ###
