"""add vector index path and embedding credential fields

Revision ID: f8628ffc61a8
Revises: e7fd71b62979
Create Date: 2026-08-04 18:13:24.869461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8628ffc61a8'
down_revision = 'e7fd71b62979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vector_index_path', sa.String(), nullable=True))

    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'embedding_use_completion_credentials', sa.Boolean(), nullable=False, server_default=sa.true()
            )
        )
        batch_op.add_column(sa.Column('embedding_api_key', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_column('embedding_api_key')
        batch_op.drop_column('embedding_use_completion_credentials')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('vector_index_path')

    # ### end Alembic commands ###
