"""Add conversation_messages table and course stage/parent_course_id

Revision ID: ff940063365a
Revises: 9a396a383314
Create Date: 2026-07-31 07:22:23.331839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff940063365a'
down_revision = '9a396a383314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stage', sa.String(), nullable=False, server_default='active'))
        batch_op.add_column(sa.Column('parent_course_id', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_courses_parent_course_id', 'courses', ['parent_course_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_courses_parent_course_id', type_='foreignkey')
        batch_op.drop_column('parent_course_id')
        batch_op.drop_column('stage')

    op.drop_table('conversation_messages')
    # ### end Alembic commands ###
